### ISSUE TITLE
Why not combine HEAD/GET with same path to single line?

### ISSUE THREAD

**Issue by luckyxhu** [ShogunPanda/fastify-print-routes#2]
The plugin is great! 

Why not combine HEAD/GET with same path to single line?
When project has many routes, combine same path to single line can save many space, and more clear.

thanks.

**Comment by ShogunPanda** [comment]
Hello!
First of all, thanks the compliments 😀 

It's a very good idea. I think I will introduce it next week. 

The only thing is that I won't make enabled by default as I think it might confuse people. But it will be an opt-in option.

You will hear from me soon 🤣

**Comment by luckyxhu** [comment]
thanks, wait for your message.

**Comment by ShogunPanda** [comment]
I just added the `compact` option to the plugin which should solve this issue.
See [version 2.1.0](https://github.com/ShogunPanda/fastify-print-routes/releases/tag/v2.1.0)
