### ISSUE TITLE
Maybe a Query column?

### ISSUE THREAD

**Issue by aronlabr** [ShogunPanda/fastify-print-routes#4]
Thanks for the plugin, very practical and stylish.

While using the `schema` object to define `query` params , Could be possible to show a Query column as an option? 

Maybe set it to be displayed via `config` or and option to plugin

I understand that this is not for docs api like swagger and it could be out of scope for the project. 

**Proposal**:
```
method: 'GET',
url: '/',
schema: {
  query: {
    type: 'object',
    properties: {
      query1: { type: 'integer' },
     query2: { type: 'integer' },
    }
  }
},
config: {
  query: true
}
```

|Methods | Path | Queries |
|--|--|--|
|GET | / | query1, query2| 

There could be some issues with many params or if each method has different params. 

Note: Per my understanding, using query params for other than GET is not a good idea

**Comment by ShogunPanda** [comment]
Sorry for the long wait, this is now available in https://github.com/ShogunPanda/fastify-print-routes/releases/tag/v3.1.0 - The querystring will be print as part of the URL.

About your note, AFAIK is not really an issue.
