### ISSUE TITLE
Allow options to ignore certain routes based on patterns

### ISSUE THREAD

**Issue by CdTgr** [ShogunPanda/fastify-print-routes#5]
Thanks for the package, its really a useful tool to debug routes.

When listing the routes all the routes including the swagger routes are listed.

From what I see on the configuration there is a `hide` flag, unfortunately swagger routes are not defined as routes but the plugin [@fastify/swagger-ui](https://www.npmjs.com/package/@fastify/swagger-ui) itself.

It would be nice to have a configuration that removes certain routes from listing.

eg:
```typescript
await server.register(FastifySwagger, {
  swagger: {}
})
```

```typescript
await server.register(fastifyPrintRoutes, {
  excludePattern: '^/v1/docs' // <-- could be a regular expression.
})
```

**Comment by CdTgr** [comment]
```typescript
await server.register(fastifyPrintRoutes, {
  excludePattern: '^/v1/docs',
})
```

```typescript
const exclude = excludePattern ? new RegExp(excludePattern) : undefined
```

```typescript
routes = routes.filter(r => getRouteConfig(r).hide !== true && !exclude?.test(r.url)).sort(sortRoutes)
```

**Comment by ShogunPanda** [comment]
Hi!
In https://github.com/ShogunPanda/fastify-print-routes/releases/tag/v3.1.0 I added a `filter` function to the options. It's more generic than using RegExps but you can achieve the same with a oneliner: `filter(route) { return !/^\/v1\/docs/.test(route.url) }`.
